Add new tutorial: Web Scrape Amazon with Beautiful Soup
codedex-io/projects pull request #10
Opened 2022-10-15 10:17 UTC by ashutoshkrris

Closes issue 

- [x] My project tutorial topic has already been approved by the Codédex team
- [x] My project tutorial file renders properly in `mdx`
- [x] The content written is my own, and not plagiarized from other sources
- [x] All code written is commented or documented thoroughly
- [x] I have already completed a self-review of the project tutorial 
- [x] I will comply with changes from the Codédex team about my project tutorial

2022-10-15 19:44 UTC, sonnynomnom reviewed
Hi @ashutoshkrris! Awesome draft! Can't believe you got most of the formatting down. 🙌

Anyway, I just left my review. Let me know when you are done with the changes and another team member can take a look! 🙏

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +  - webscraping
Great job on the metadata! This is awesome. And let's take out the `webscraping` tag.

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +**Versions:** Python 3.10, requests 2.28.1, beautifulsoup4 4.11.1, lxml 4.9.1
```suggestion
**Versions:** Python 3.10, requests 2.28.1, beautifulsoup4 4.11.1, lxml 4.9.1  
```

I added two spaces after so that Read Time go on a new line.

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +Have you ever missed an Amazon product that was available at a discounted price? Have you ever thought of building an application that notifies you when the price of an Amazon product decreases below
Like the hook!

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +In this tutorial, we will learn to build a web scraper that scrapes Amazon product details using [Beautiful Soup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/).
I think we should explain Beautiful Soup (1-2 sentences) either here or in the **What is Web Scraping?** section?

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +First, open a Python code editor of your choice (VS Code recommended), and create a new Python file `scraper.py`. This is where we will be writing our code to scrape Amazon.
```suggestion
First, open a Python code editor of your choice (VS Code recommended), and create a new Python file **scraper.py**. This is where we will be writing our code to scrape Amazon.
```

We haven't put this in the Contribution Guidelines yet, but file names on Codédex should be bold!

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +### Extracting the title of the product
Can we do title case for every header?

```suggestion
### Extracting the Title of the Product
```

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +Open a product page, say [this one](https://www.amazon.com/Acer-Chromebook-Graphics-802-11ac-CB512-C1KJ/dp/B09Q9YKW15/ref=lp_16225007011_1_2) on your browser, and use the **Inspect Element** option t
Can we just show an image here of the Amazon Product page?

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +Open a product page, say [this one](https://www.amazon.com/Acer-Chromebook-Graphics-802-11ac-CB512-C1KJ/dp/B09Q9YKW15/ref=lp_16225007011_1_2) on your browser, and use the **Inspect Element** option t
And then in the text, tell them how to get to the Inspect Elements. Like:

- On Windows: blah blah.
- On Mac: blah blah.

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +Now comes the most important part of the tutorial where we will extract data from the page. For the sake of this tutorial, we will extract two data - the **title** of the product and the **price** of
```suggestion
Now comes the most important part of the tutorial where we will extract data from the page. For the sake of this tutorial, we will extract two data:

 - The **title** of the product.
 - The **price** of the product.
```

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +We split the `extracted_price` string using the **$** symbol and select the element at index 1. We also add the dollar symbol before the price.
```suggestion
We split the `extracted_price` string using the `$` symbol and select the element at index 1. We also add the dollar symbol before the price.
```

Also should we briefly (in a few words) explain the $ sign?

2022-10-15 19:44 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +We use the `find()` method to find a `span` element. We pass the id **productTitle** in a dictionary called `attrs` that accepts the attributes. The `get_text()` method returns the text in a string f
```suggestion
We use the `.find()` method to find a `span` element. We pass the `productTitle` id in a dictionary called `attrs` that accepts the attributes. The `.get_text()` method returns the text in a string format. The `.strip()` method is used to remove any extra whitespaces.
```

We haven't added in the Contribution Guide, the method names have the dot in front on Codédex.

2022-10-16 03:26 UTC, Goku-kun requested changes
Hi, I've reviewed this article and think we need to make some more basic changes before this goes live.

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +**Prerequisites:** Python fundamentals, Basics of HTML
Can we keep this "Python fundamentals, HTML basics"? Just to maintain uniformity

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +![Demo](demo.gif)
Need to update this URL with the absolute URL from GitHub.

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +When we send an HTTP request, we send some **headers** along with the request. If you go to the Network tab of your browser and reload any web page, you can find the request headers similar to below:
The second sentence can sound confusing if someone who hasn't worked with DevTools is reading this article.

We can rephrase this as: "If you open devtools in your browsers(usually accessible through Command + Option + C or Control + Shift + C or F12 key) and switch to the network tab and reload any page, you can find the request headers that are similar to the ones shown below:"

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +![Request Headers](request-headers.png)
Need to change this URL with the absolute URL.

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +```
Need to link the Beautiful Soup documentation with details about the Soup object.

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +Open a product page, say [this one](https://www.amazon.com/Acer-Chromebook-Graphics-802-11ac-CB512-C1KJ/dp/B09Q9YKW15/ref=lp_16225007011_1_2) on your browser, and use the **Inspect Element** option t
"Inspect Element" -> "Right click on the title of the page and select the 'Inspect Element' option from the dropdown menu"

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +![Extracting Title](extracting-title.png)
Replace the image link with the absolute URL.

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +We use the `find()` method to find a `span` element. We pass the id **productTitle** in a dictionary called `attrs` that accepts the attributes. The `get_text()` method returns the text in a string f
The `strip()` method is used to remove any extra leading and trailing whitespaces.

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +Similar to the title of the product, if you inspect the page, you will find the below HTML code for the price of the product.
Similar to the title of the product, if you inspect the prices by right clicking on them and opening devtools, you will find the below HTML code for the price of the product.

2022-10-16 03:26 UTC, Goku-kun commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +As mentioned before, the layout of a website keeps changing and hence, the above code may not be helpful in the future. But this tutorial should be helpful to teach to you how to scrape any website.
"the above code may not be helpful" -> "the above code may no longer be applicable as it is, without some changes. Join Codédex club to get support from code mentors if you run any trouble while using this article."

@sonnynomnom What do you think about this? Just the second updated sentence.

2022-10-16 04:01 UTC, ashutoshkrris commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +When we send an HTTP request, we send some **headers** along with the request. If you go to the Network tab of your browser and reload any web page, you can find the request headers similar to below:
Yes @Goku-kun 
Thanks for the suggestion.
I was going to add it after @sonnynomnom asked to.

2022-10-16 22:14 UTC, sonnynomnom commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +As mentioned before, the layout of a website keeps changing and hence, the above code may not be helpful in the future. But this tutorial should be helpful to teach to you how to scrape any website.
Yeah we can do that!

```suggestion
As mentioned before, the layout of Amazon will keep changing and hence, the above code may not be helpful in the future. Join Codédex Club to get support from code mentors if you run any trouble while using this article!
```

2022-10-17 21:54 UTC, asiqurrahman commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +The process of extracting data from a website is known as web scraping. This data is collected and then exported in a way that the user will find more valuable, say an API or a CSV file. Although web
A Hyperlink to this wiki article might be helpful for users wanting to get a deeper understanding of web scraping.

 https://en.wikipedia.org/wiki/Web_scraping

2022-10-17 22:12 UTC, asiqurrahman commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +Now, let us make an HTTP request to get the HTML content of the product page. Using the `BeautifulSoup` class, we will create a [soup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#making-th
For me, "let us" breaks the flow of the sentence. "Now, let's make" would sound better I think.
This is subjective of course.

2022-10-18 04:50 UTC, asiqurrahman commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +We use the `.find()` method to find a `span` element. We pass the `productTitle` id in a dictionary called `attrs` that accepts the attributes. The `.get_text()` method returns the text in a string f
Replace "we" with "Then" in the second sentence.

2022-10-18 04:56 UTC, ashutoshkrris commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +We use the `.find()` method to find a `span` element. We pass the `productTitle` id in a dictionary called `attrs` that accepts the attributes. The `.get_text()` method returns the text in a string f
Done @asiqurrahman

2022-10-18 05:21 UTC, asiqurrahman commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +But before extracting, let us learn how to view the HTML code that makes up any web page. Open a product page, say [this one](https://www.amazon.com/Acer-Chromebook-Graphics-802-11ac-CB512-C1KJ/dp/B0
"let us" --> "let's"

2022-10-18 05:22 UTC, asiqurrahman commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +As mentioned before, the layout of Amazon will keep changing and hence, the above code may not be helpful in the future. Join Codédex Club to get support from code mentors if you run any trouble whil
"if you run any trouble" should be "if you run into any trouble".

That should be my final feedback.
Amazing article, loved the pace of it and how easy it is to understand!

2022-10-18 05:27 UTC, ashutoshkrris commented on projects/web-scrape-amazon-with-beautiful-soup/web-scrape-amazon-with-beautiful-soup.mdx
> +As mentioned before, the layout of Amazon will keep changing and hence, the above code may not be helpful in the future. Join Codédex Club to get support from code mentors if you run any trouble whil
Great, thank you @asiqurrahman 
I've made the required changes.

2022-10-19 05:15 UTC, Goku-kun approved these changes
I think we're ready to publish this article now.

I'm merging this in!

2022-10-19 05:15 UTC, merged

2022-10-19 05:23 UTC, ashutoshkrris commented
Awesome
Thanks, @Goku-kun and the entire Codédex team.