Todo App Project
codedex-io/projects pull request #121
Opened 2023-11-06 04:01 UTC by mdwiltfong

Closes #92 

- [x ] My project tutorial topic has already been approved by the Codédex team.
- [ ] My project tutorial file renders properly in `mdx`.
- [x ] My `.mdx` file follows the [project template](https://github.com/codedex-io/projects/tree/main/docs/project_template.mdx), as well as what's recommended in the [content guidelines](https://github.com/codedex-io/projects/tree/main/docs/content_guidelines.mdx).
- [x ] The content written is my own, and not plagiarized from other sources.
- [x ] All code written is thoroughly functional and commented (or documented).
- [ ] I have already completed a self-review of the project tutorial. 
- [x ] I will comply with changes made or recommended by the Codédex team about my project tutorial.

2023-11-06 04:02 UTC, mdwiltfong commented
WIP

2023-11-06 04:07 UTC, mdwiltfong commented
@Dusch4593 , the link to the `project-template.mdx` in the contributing guide leads to a 404. I think it's just because the template is under `/docs` versus the root. I can fix this in this PR. Would the URL be `/main/docs/project-template.mdx`?

2023-11-06 13:35 UTC, Dusch4593 commented
Hey @mdwiltfong! Thanks for flagging this!

No need to make that change in this PR; I went ahead and made it here in aaa906c8fb4e4b14306e619a1445ef55482fbaeb. It turned out there also needed to be an underscore in `project_template.mdx` (not a dash).

2023-11-07 02:52 UTC, mdwiltfong commented
Whoops! I was trying to be fancy squash some of my commits but I ended up mixing some commits 😬 Nonetheless this PR is ready for review @Dusch4593 !

2023-11-07 19:52 UTC, Dusch4593 requested changes
Hey @mdwiltfong I just finished a first review of this PR! Let us know if you have any questions about the comments/suggestions left for you here. I also emailed you with some more overall feedback.

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +Now that your debugger is at a good state, you can refer to the project’s repo to set up your workspace. The `main` branch will contain the three files we will need for the project. You can either co
Not sure if I missed it, but was there a link to the project's repo provided in this file?

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +Right now we are triggering the function through the typical pattern of using `.addEventListener` on the form element, but how do we convert the `event` object into the data we need? We could add a `
```suggestion
Right now we are triggering the function through the typical pattern of using `.addEventListener()` on the form element, but how do we convert the `event` object into the data we need? We could add a `console.log()` to see what an `event` looks like, but how about we use our debugger instead? Let’s try it!
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +Let’s add a “breakpoint” in `addTodo()` beside `event.preventDefault()`. You can do this by clicking to the left of the line number. You’ve done it correctly when you see a red dot appear.
```suggestion
Let’s add a “breakpoint” in `.addTodo()` beside `event.preventDefault()`. You can do this by clicking to the left of the line number. You’ve done it correctly when you see a red dot appear.
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +Nice! Now that we have launched our app in the debugger, and our breakpoint set, let’s trigger the `addTodo` method by clicking on the “Add Todo” button. If you look back at your VS Code, you'll see
```suggestion
Nice! Now that we have launched our app in the debugger, and our breakpoint set, let’s trigger the `.addTodo()` method by clicking on the “Add Todo” button. If you look back at your VS Code, you'll see that our breakpoint was triggered! As a result, we can see what some of the variables are at this point in the `.addTodo()` method, such as `event`.
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +It looks like `event.target` has conveniently captured all the elements in our form. That means, we could call on these elements individually and obtain their `.value` properties. Let’s try modifying
```suggestion
It looks like `event.target` has conveniently captured all the elements in our form. That means, we could call on these elements individually and obtain their `.value` properties. Let’s try modifying our `.addTodo()` function like this:
```

I also noticed that you use `.addTodo()` **function** here whereas you would previously use `.addTodo()` **method**. Let's just use either function or method.

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +You might be wondering why we are copying the `todos` array with the spread operator. In order to reduce side effects introduced directly by our functions, we need to copy the passed in `todos` array
```suggestion
You might be wondering why we are copying the `todos` array with the spread operator. In order to reduce side effects introduced directly by our functions, we need to copy the passed in `todos` array, and then return the copy. This ties into why we created an anonymous function as the listener for the `.addEventListener()` function, because it then allowed us to pass in the original `todos` array.
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +}
```suggestion
function generateTodoHTML(todo) {
  return `
    <div class="card-body">
      <h5 class="card-title">${todo.todoTitle}</h5>
      <h6 class="card-subtitle mb-2 text-muted">${todo.todoDate}</h6>
      <h6 class="card-subtitle mb-2 text-muted">${todo.todoNumOfPeople}</h6>
      <p class="card-text">${todo.todoDescription}</p>
      <button class="btn btn-primary">Done</button>
      <button class="btn btn-danger">Delete</button>
    </div>
  `;
}
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +Although, this event listener will intercept all clicks. In order to make sure that it only works when the “Done” button is clicked, we will add an if-statement that checks the `id` attribute of the
```suggestion
However, this event listener will intercept all clicks. In order to make sure that it only works when the “Done” button is clicked, we will add an `if`-statement that checks the `id` attribute of the `event` object.
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +    // Core logic to remove task from state and then re-render todo list
```suggestion
    // Code to remove task from state and then re-render todo list
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +Let’s test our software! Let’s create scenarios that will target the various if statements we created in `validateTodo()`. We can do this by first filling out the form, except its title. Once we subm
```suggestion
Let’s test our software by creating scenarios that target the various `if`-statements we created in `validateTodo()`. We can do this by first filling out the form, except its title. Once we submit the form, an alert should appear saying that the title needs to have a minimum length of 5 characters.
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +Taking a look at `Date.now()` it looks like we need to modify our approach. `Date.now()` is a function that returns the number of seconds that have elapsed since 1 January 1970. This explains why our
```suggestion
It looks like we need to modify our approach. The `Date.now()` function returns the number of seconds that have elapsed since January 1st, 1970. This explains why our `if`-statement isn’t stopping users from picking dates in the past, because it’s essentially comparing a string to a number. Instead of storing the output of our date field directly in a variable, we need to package it in a `Date` object. That way, we can convert the string to epoch time. We can do this by simply passing the value of `event.target.value` to the `Date` object before assigning it to `todoDate` in the `addTodo()` function. Your `addTodo()` function should look like the code below:
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +It looks like passing an empty string to `Date()` is causing it to assign a string of “Invalid Date” to `todo.todoDate` . We will quickly resolve this by adding another if statement that checks if `t
```suggestion
It looks like passing an empty string to `Date()` is causing it to assign a string of “Invalid Date” to `todo.todoDate`. We will resolve this by adding another `if`-statement that checks if `todo.todoDate` is equal to “Invalid Date”, then push the error message “Date must be in the format of YYYY-MM-DD" to the `errors` array.
```

2023-11-07 19:52 UTC, Dusch4593 commented on projects/build-a-todo-app-and-setup-js-debugger-in-vscode/build-a-todo-app-and-setup-js-debugger-in-vscode.mdx
> +Your ` validateTodo()` should look like this:
```suggestion
Your `validateTodo()` should look like this:
```

2023-11-07 20:55 UTC, mdwiltfong commented
Thanks @Dusch4593 ! 

I'll go ahead and address those comments and look at the email you sent.

2023-11-08 19:26 UTC, Dusch4593 commented
> Thanks @Dusch4593 !
> 
> I'll go ahead and address those comments and look at the email you sent.

Sounds great, @mdwiltfong! Let us know if you have any questions! 😄

2023-11-11 04:40 UTC, mdwiltfong commented
Woah! I was able to squash my commits! So proud of myself 😎 

@Dusch4593 Would you be so kind to give this another review?

2023-11-13 11:28 UTC, Dusch4593 requested changes

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +In order to learn about debugging, we will need faulty software to debug. In this [repo](https://github.com/mdwiltfong/codedex_todo/tree/development) we have a todo app that has a bug built into it.
```suggestion
In order to learn about debugging, we will need buggy code. In this [repo](https://github.com/mdwiltfong/codedex_todo/tree/development) we have a todo app that has a bug built into it. To be specific, the app allows users to enter todo dates in the past, which does not make sense in the context of the app's purpose to help users setup tasks for the future!
```

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +Ideally we would want the app to alert the user of this incorrect data.
```suggestion
Ideally, we would want the app to alert the user of this invalid data.
```

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +The todo app consists of 5 functions, `addTodo()`, `renderTodos()`,`generateTodoHTML()`,`completeTodo()`,and `validateTodo()`. You can deduce their purposes from their names, but the main functions w
```suggestion
The todo app consists of five functions:

- `addTodo()`
- `renderTodos()`
- `generateTodoHTML()`
- `completeTodo()`
- `validateTodo()`

You can deduce their purposes from their names, but the main functions we will be focusing on is `addTodo()` and `validateTodo()`.
```

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +A common strategy to debugging software is using breakpoints. A breakpoint is essentially a point in your software that you would like to pause the execution of your code. This allows you to inspect
```suggestion
A common strategy to debugging software is using **breakpoints** to essentially tell your code where you would like to pause the execution of your code. This allows you to inspect the state of your application at that point in time. In VS Code, you can set a breakpoint by clicking on the line number of the line you want to pause your code at. You can also set a breakpoint by right-clicking the line number and selecting "Add Breakpoint."
```

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +More importantly you will have to launch the app with VS Code's debugger. With this app it's as simple as clicking a button! First, open `index.html` and then click on the "Run and Debug" button in t
```suggestion
More importantly, you will have to launch the app with VS Code's debugger. With this app, it's as simple as clicking a button! First, open **index.html** and then click on the "Run and Debug" button in the "Run and Debug" extension. Your screen should look similar to the image below:
```

When referring to files or directories, let's bold instead of use backticks. 😄

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +The widget contains a series of buttons which we will use. From left to right, we have "Pause", "Step Over", "Step Into", "Step Out", "Restart" and "Stop." Keep in mind that the "Pause" button will b
```suggestion
The widget contains a series of buttons which we will use. From left to right, we have:

- "Pause"
- "Step Over"
- "Step Into"
- "Step Out"
- "Restart"
- "Stop"

Keep in mind that the "Pause" button becomes a "Play" button (a green arrow) when the debugger is at a breakpoint, and the app will stay this point until you press "Play." We will be exploring "Step Over" and "Step Into" in this tutorial.
```

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +Let's add a breakpoint beisde the if-statement that checks `todo.todoDate` is less than `Date.now()`. Then, let's create a todo with a todo date in the past. VS Code should pause the app at your brea
```suggestion
With our app launched in the debugger, and a basic understanding of the app and the issue, let's begin debugging!

Let's add a breakpoint beside the if-statement that checks `todo.todoDate` is less than `Date.now()`. Then, let's create a todo with a date from the past. VS Code should pause the app at your breakpoint, and allow you to see the values of the variables until that point.
```

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +This fix will take place in two places. In `addTodo` and in `validateTodo`.
```suggestion
Our app is indeed picking up the date the user is inputing, but it is assigning a string! Considering that `Date.now()` returns a number, the app is expecting `todo.todoDate` to be a number as well. This would explain why the if-statement is not picking up this error. The best way to solve this through the `Date` object.

`Date.now()` specifically returns the date in "epoch time", or the number of seconds since January 1st, 1970. If we passed in the date as a string into the `Date` object, we can take advantage of the various helper functions in `Date` to convert the string into epoch time. Such as the `.getTime()` method.

This fix will take place in two places: in `addTodo()` and in `validateTodo()`.
```

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +With this fix in place, let's remove the breakpoint (you can do this by clicking on the red dot itself), and then test whether the alert box will appear if we enter a todo date in the past. After you
```suggestion
With this fix in place, let's remove the breakpoint (you can do this by clicking on the red dot itself) and then test whether the alert box will appear if we enter a todo date in the past. After you confirm this, let us test one other scenario.
```

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +To see what `event.target[2].value` equals, you can place your mouse over `.target[2]` and modal will appear. This modal represents `.target`. If you access the second element in the `.target` array,
```suggestion
As we can see on the left hand side, `todo.todoDate` is being assigned a value of `Invalid Date`. This is a hint that something is not being correctly passed into `new Date()` in `addTodo()`. Let's add a breakpoint at `const todoDate = new Date(event.target[2].value);` to see what's being passed into `new Date()` and then recreate the scenario that is causing the bug. This breakpoint is a little more involved than the others, mainly because the `event` object is multi-layered.

To see what `event.target[2].value` equals, you can place your mouse over `.target[2]` and modal will appear. This modal represents `.target`. If you access the second element in the `.target` array, and the search for the `.value` property, you will see the app is passing an empty string.
```

Doesn't "second element" refer to the 1st index of an array? Should we change "second element in the `.target` array" to "third element in the `.target array" since we're working with `event.target[2].value`?

2023-11-13 11:28 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +Excellent! We not only identified the reason causing the bug, but we were able to resolve it as well! At this point you have learned how to use VS Code to debug web apps using vanilla javascript, as
```suggestion
Excellent! We not only identified the reason causing the bug, but we resolved it as well! At this point, you have learned how to use VS Code to debug web apps using vanilla JavaScript, as well generic debugging strategies that you can use in any other app.

If you are interested in learning more about debugging in VS Code, you can always refer to Microsoft's [documentation](https://code.visualstudio.com/docs/nodejs/browser-debugging).
```

2023-11-13 15:43 UTC, mdwiltfong commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +To see what `event.target[2].value` equals, you can place your mouse over `.target[2]` and modal will appear. This modal represents `.target`. If you access the second element in the `.target` array,
100%

2023-11-13 16:13 UTC, mdwiltfong commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +<RoundedImage
<img width="334" alt="activity-bar-example" src="https://github.com/codedex-io/projects/assets/76107997/c2711c01-855b-4ffc-b6ed-b5380de0f3c2">

Sure! Let me know what you think of this image

2023-11-13 16:22 UTC, mdwiltfong commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +To see what `event.target[2].value` equals, you can place your mouse over `.target[2]` and modal will appear. This modal represents `.target`. If you access the second element in the `.target` array,
Maybe I should generate a gif for this part. Any advice how I can do that?

2023-11-13 16:34 UTC, mdwiltfong commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +To see what `event.target[2].value` equals, you can place your mouse over `.target[2]` and modal will appear. This modal represents `.target`. If you access the second element in the `.target` array,
![GMP_Q29tcHJlc3NHSDAx_4](https://github.com/codedex-io/projects/assets/76107997/f5119090-045e-4975-a001-fe9b535dfedd)

 My wife was able to make one but I think this might be too much due to the low quality. Might just stick with the image and change the language.

2023-11-13 16:36 UTC, mdwiltfong commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +To see what `event.target[2].value` equals, you can place your mouse over `.target[2]` and modal will appear. This modal represents `.target`. If you access the second element in the `.target` array,
![Exported](https://github.com/codedex-io/projects/assets/76107997/c64cb8fc-0d25-4d89-ae31-cc6de5ee5eb0)
Spoke too soon! I'll add this gif and update the language for clarity.

2023-11-13 17:22 UTC, mdwiltfong commented
@Dusch4593 thanks for the comments! Let me know what you think with the changes i've made

2023-11-13 20:07 UTC, Dusch4593 requested changes
Hey @mdwiltfong, thanks for following up with those changes. Here are a few more comments/suggestions from me; this is looking great! 🚀

2023-11-13 20:07 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +The app is indeed picking up the date the user is inputing, but it is assigning a string! Considering that `Date.now()` returns a number, the app is expecting `todo.todoDate` to be a number as well.
```suggestion
The app is indeed picking up the date the user entered, but it is assigning a string! Considering that `Date.now()` returns a number, the app is expecting `todo.todoDate` to be a number as well. This would explain why the `if`-statement is not picking up this error. The best way to solve this is through the `Date` object.
```

2023-11-13 20:07 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +Let's add a breakpoint beside the if-statement that checks `todo.todoDate` is less than `Date.now()`. Then, let's create a todo with a date from the past. VS Code should pause the app at the breakpoi
```suggestion
With our app launched in the debugger, and a basic understanding of the issue, let's begin debugging!

Let's add a breakpoint at line 73, beside the `if`-statement that checks if `todo.todoDate` is less than `Date.now()`. Then, let's create a todo with a date from the past. VS Code should pause the app at the breakpoint, and allow you to see the values of the variables until that point.
```

2023-11-13 20:07 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +As we can see on the left hand side, `todo.todoDate` is being assigned a value of `Invalid Date`. This is a hint that something is not being correctly passed into `new Date()` in `addTodo()`. Let's a
> Let's add a breakpoint at `const todoDate = new Date(event.target[2].value);`...

I would personally refer to the actual line number along with the name of the file. So in this case, I would change to something like:

> Let's add a breakpoint at line 20 in **script.js** ...

2023-11-13 20:07 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +Let's resolve this by adding another if-statement in `validateTodo()` that checks if `todo.todoDate` equals `Invalid Date`.
```suggestion
Let's resolve this by adding another `if`-statement in `validateTodo()` that checks if `todo.todoDate` is equal to `Invalid Date`:
```

2023-11-13 22:40 UTC, mdwiltfong commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +<RoundedImage
<img width="177" alt="Screenshot 2023-11-13 at 5 39 28 PM" src="https://github.com/codedex-io/projects/assets/76107997/eaa2ca10-a9fc-4909-8ad8-155ffed65581">

@Dusch4593 , how's this?

2023-11-13 22:40 UTC, mdwiltfong commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +<RoundedImage
I'll add the arrow after :)

2023-11-14 14:35 UTC, Dusch4593 requested changes
Nice, @mdwiltfong! I actually went and looked at some of your other files as well and left some feedback there (along with a little more in the actual tutorial).

@sonnynomnom After changes are implemented this time around, do you want to take a look at this before we take steps to publish?

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/project/index.html
> +</html>
```suggestion
</body>
</html>
```

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/project/script.js
> +function addTodo(event, todos, validateCallback) {
```suggestion
let editForm = document.getElementById("editForm");

function addTodo(event, todos, validateCallback) {
```

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/project/script.js
> +  event.preventDefault();
In the MDX file, should have a note or something about what this line does?

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/project/script.js
> +}
```suggestion
function generateTodoHTML(todo, index) {
  return `
    <div data-se=${index} class="card-body my-2 p-2 border dorder-dark">
      <h5 class="card-title">${todo.todoTitle}</h5>
      <h6 class="card-subtitle mb-2 text-muted">${todo.todoDate}</h6>
      <h6 class="card-subtitle mb-2 text-muted">${todo.todoNumOfPeople}</h6>
      <p class="card-text">${todo.todoDescription}</p>
      <button type="click" id="done" class="btn btn-success">Done</button>
    </div>
  `;
}
```

It seemed like there was an extra closing `</div>` in there?

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/project/script.js
> +*/
```suggestion
Project memory. This will contain all the todos that are created by the user.

todo = {
  todoTitle,
  todoNumOfPeople,
  todoDate,
  todoDescription,
  isEditting
}
*/

```

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/project/index.html
> +                <input type="number" name="numofpeople" id="numofpeople">
```suggestion
                <label for="num-of-people"> Number of People Assigned</label>
                <input type="number" name="num-of-people" id="num-of-people">
```

Suggesting this because the other uses of the `for`, name`, and `id` attributes use kebab-case for their values.

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/project/index.html
> +
```suggestion
    </div>
```

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +  description="valid date solution "
```suggestion
  description="valid date solution"
```

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/project/package.json
> +}
@mdwiltfong I forget, do we need this anymore?

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +### Launch the app in VS Code's Debugger
```suggestion
### Launch the App
```

The sub-headings should always be in "Title Case" in AP Style (you can test your headings [here](https://capitalizemytitle.com/style/AP/)).

2023-11-14 14:35 UTC, Dusch4593 commented on projects/debug-your-web-app-on-vs-code/debug-your-web-app-on-vs-code.mdx
> +# Setup JS Debugger in VS Code
```suggestion
# Debug Your Web App on VS Code
```

This level 1 heading should match what is in the `title` on line 2.

2023-11-14 15:08 UTC, mdwiltfong commented
> Nice, @mdwiltfong! I actually went and looked at some of your other files as well and left some feedback there (along with a little more in the actual tutorial).

No worries! I'll try and wrap those up during lunch.

2023-11-14 18:09 UTC, mdwiltfong commented
Nice! Let me know what you guys think! 

@Dusch4593 @sonnynomnom

2023-11-16 16:36 UTC, merged