First draft of Not Hot Dog
codedex-io/projects pull request #34
Opened 2022-11-17 22:48 UTC by avb-is-me

Closes issue 

- [ ] My project tutorial topic has already been aproved by the Codédex team
- [ ] My project tutorial file renders properly in `mdx`
- [ ] The content written is my own, and not plagiarized from other sources
- [ ] All code written is commented or documented thoroughly
- [ ] I have already completed a self-review of the project tutorial 
- [ ] I will comply with changes from the Codédex team about my project tutorial

2022-11-18 22:40 UTC, asiqurrahman commented
Great project and idea. Love it, the code itself is amazing, but let's put a little more time into explaining what the code actually does, rather than just a one-liner. Take a look at this project right here as an example:

https://www.codedex.io/projects/generate-a-blog-with-openai

Let's also re-write the introduction. The introduction should be a small summary of what the reader can expect to get out of the article, the tools they'll use along the way, etc. 

And here are some more feedback:

- Prerequisites formatting needs fixing
- Let's change the Read time to 30 minutes, instead of 10
- detcting -> detecting
- just like Jian Yang -> just like Jian Yang from Silicon Valley
- Spend less time on creating project file. You can just say create a python file named ___.
- Explain what a virtual environment is and link it to the Wikipedia page.
- Add a one-liner about what Flask is.
- touch is linux only, what about windows and mac?
- Were importing in a lot of things in line 104, what are these, and what are there purpose? You can put them in a list beforehand and explain what they're used for.
- From line 104 and onwards we have alot of code and just a one liner saying what it is but were not explaining it, the purpose for it or why we coded it the way we did, etc. Let's try to explain the code as much as we can.
- API_URL = os.getenv("HUGGING_FACE_API_URL"), were injecting env variables without mentioning it previously or explaining where it comes from.
- We mention creating env variables at the end, this should be moved to the top of the article
- Hugging face api url is at the end of the project, an error

2022-11-22 15:53 UTC, avb-is-me commented
Working on changes, also touch works on mac as well

2022-11-26 21:44 UTC, avb-is-me commented
@asiqurrahman Just made changes!  Let me know what you think!

2022-12-01 04:53 UTC, sonnynomnom reviewed
Just did a quick review #2 @Andrewvanbeek!

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +title: Detect Not Hot Dogs with hugging face API
```suggestion
title: Detect Not Hot Dogs with Hugging Face API
```

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +description: Create your own not-hotdog classifier
```suggestion
description: Create your own "Not Hotdog" classifier to help Jian Yang from Silicon Valley.
```

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +description: Create your own not-hotdog classifier
Something like this i think ^

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +
Delete extra newline.

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Introduction:
```suggestion
## Introduction
```

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +Now run the project again and upload bannanas or anything not bannanas.
Let's have a Conclusion section after everything:

See the bottom here:

https://github.com/codedex-io/projects/blob/main/projects/build-a-discord-bot-with-python/build-a-discord-bot-with-python.mdx

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +**Prerequisites:**
```suggestion
**Prerequisites:** Hugging Face account, Python 3  
```

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +Unlock the power of innovation around detecting if an image is a hot dog or a "not hot dog" just like Jian Yang from Silicon Valley using machine learning models on hugging face.  To do this we will
```suggestion
Unlock the power of innovation around detecting if an image is a hot dog or a "not hot dog" just like Jian Yang from Silicon Valley using machine learning models on hugging face.  

[add YouTube embed or GIF here]

To do this we will be using [Hugging Face](https://huggingface.co/), a community and platform that hosts a bunch of open source machine learning models, datasets, and more.

Let's get started! 🌭
```

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +Unlock the power of innovation around detecting if an image is a hot dog or a "not hot dog" just like Jian Yang from Silicon Valley using machine learning models on hugging face.  To do this we will
Can we do something like this? Add add YouTube embed or GIF link here.

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Create a nothotdog directory:
## Setting Up

Create a new directory named `nothotdog`.  This is where our project will live.

Next, enter your directory in the terminal, so we can start getting ready for our code:

```bash
cd nothotdog
```

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Create a nothotdog directory:
I think the two sections can be combined like so ^

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Activate the virtual environment
```suggestion
Now, let's activate the virtual environment:
```

Let's take out the heading and turn it into a sentence.

2022-12-01 04:53 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +In the templates folder create an index.html file.
Bold all file names (https://github.com/codedex-io/projects/blob/main/.github/CONTRIBUTING.md#formatting)

2022-12-01 04:59 UTC, sonnynomnom commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +  - beginner
```suggestion
  -  intermediate
```

2022-12-02 05:24 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +\-A hugging Face Account
**Prerequisites:** Hugging Face, Python fundamentals

You don't need to specify the account, since we're using the library in general

2022-12-02 05:26 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +Lets create a virtual environment or venv, which is a isolated environment that contains a Python installation in addition to other packages.  If you want to learn more check out this [Link](https://
```suggestion
Let's create a virtual environment or `venv`, which is an isolated environment that contains a Python installation in addition to other packages.  If you want to learn more check out this [Link](https://link-url-here.org](https://docs.python.org/3/tutorial/venv.html).
```
Can we also put a link for "virtual environment" here?

2022-12-02 05:26 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Install the flask
```suggestion
## Install Flask
```

2022-12-02 05:27 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +Now we are going to install flask which is a web framework in Python that makes it easy create to web applications and APIs.  Here is a [Link](https://flask.palletsprojects.com/en/2.2.x/) if you want
```suggestion
Now we are going to install Flask, which is a web framework in Python that makes it easy create to web applications and APIs. You can read more about it [here](https://flask.palletsprojects.com/en/2.2.x/).
```

2022-12-02 05:27 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Lets create a templates folder for out html
```suggestion
## Create a templates folder for HTML
```

2022-12-02 05:30 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Lets create a templates folder for out html
Add title case, and uppercase HTML. 
For the future, make sure that your headings don't start with "let's". 
"Create ..." is a better heading.

2022-12-02 05:31 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Create a file called index.html.
This heading and the next heading can be removed, and replaeced with regular text.

2022-12-02 05:31 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +Create an `.env` file at the root of the project.  This is where we will place our hugging face variables
```suggestion
Create an `.env` file at the root of the project. This is where we will place our Hugging Face variables.
```

2022-12-02 05:32 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +Open the env variable add `HUGGING_FACE_API_URL= `and `HUGGING_FACE_API_KEY=`. This is where we place the hugging face information. We can actually fill the url with the prefilled model we are using.
```suggestion
Open the .env file and add `HUGGING_FACE_API_URL= `and `HUGGING_FACE_API_KEY=`, ading in your API key and URL. This is where we place the hugging face information. We can actually fill the url with the prefilled model we are using.
```

2022-12-02 05:33 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +```shell
Can we do this without Linux? We can just tell the user to create a server file any way they want, they don't have to use bash.

2022-12-02 05:34 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +We are using a flask, and couple of built in libaries to handle files and json.
```suggestion
We are using Flask, and a couple of built in libaries to handle file types like json.
```

2022-12-02 05:34 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +We are using a flask, and couple of built in libaries to handle files and json.
Make sure that Flask and other libraries/platforms are used as uncountable nouns.

2022-12-02 05:36 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +We are using a flask, and couple of built in libaries to handle files and json.
Also, these libraries' use cases can definitely be elaborated upon further.

2022-12-02 05:37 UTC, Bobliuuu commented
@avb-is-me Just reviewed your tutorial! Very nice work. 👏 

As a few general comments, make sure to run your tutorial through a spell checker, there are still quite a few gramatical errors. Make sure to explain buzz words adequately, and use heading sparingly. 

Please let me know if you have any questions!

2022-12-06 16:05 UTC, avb-is-me commented
@sonnynomnom @Bobliuuu Please review changes

2022-12-13 22:59 UTC, Bobliuuu requested changes
Hey Andrew, content wise it looks a lot better! 
Would you mind fixing some of the grammar issues? Running it through a service like Grammarly would help on that front. 
Let me know once you've made the changes.

2022-12-13 22:59 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +Let's create a virtual environment or `venv`, which is an isolated environment that contains a Python installation in addition to other packages.  If you want to learn more check out this [Link](http
```suggestion
Let's create a virtual environment or `venv`, which is an isolated environment that contains a Python installation in addition to other packages. If you want to learn more check out this [link](https://docs.python.org/3/tutorial/venv.html).
```

2022-12-13 22:59 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +We also have install `dotenv` which we use to load environment variables.  You can find the packlage link [here](https://pypi.org/project/python-dotenv/).
```suggestion
We also have install the `dotenv` library which we use to load environment variables.  You can find the packlage link [here](https://pypi.org/project/python-dotenv/).
```

2022-12-13 22:59 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +The last package we have to add is `requests` which is a libary to handle http requests.  You can find the packlage link [here](https://pypi.org/project/requests/).
```suggestion
The last package we have to add is `requests` which is a libary to handle http requests. You can find the packlage link [here](https://pypi.org/project/requests/).
```

2022-12-13 22:59 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +In flask, if we are going to have HTML files we typically store them in a folder called templates so flask can find it.  Create a folder called templates.  It should look like below.
```suggestion
In Flask, if we are going to have HTML files we typically store them in a folder called templates so Flask is able to find them.  Create a folder called templates, which should end up looking like this: 
```

2022-12-13 22:59 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Create a file called index.html.
```suggestion
## Create a file called index.html
```

2022-12-13 22:59 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +It is important to note `method="post" action="{{ url_for('upload') }}"` in our form.  This tells our form two things, what action we want to do which is `POST` and what API route to send our data wh
```suggestion
It is important to note `method="post" action="{{ url_for('upload') }}"` in our form. This tells our form two things: what action we want to perform which is `POST` and what API route to send our data which is going `/upload`.
```

2022-12-13 22:59 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +Open the .env file and add `HUGGING_FACE_API_URL= `and `HUGGING_FACE_API_KEY=`, ading in your API key and URL. This is where we place the hugging face information. We can actually fill the url with t
```suggestion
Open the `.env` file and add `HUGGING_FACE_API_URL= `and `HUGGING_FACE_API_KEY=`, ading in your API key and URL. This is where we place the hugging face data to allow us to use hugging face's models. 
```

2022-12-13 22:59 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +At the root of our folder create a file called `web.py`.  This is where all of our `flask` server code will live.
```suggestion
At the root of our folder create a file called `web.py`. This is where all of our Flask server code will be.
```

2022-12-13 22:59 UTC, Bobliuuu commented on projects/detect-not-hot-dogs-with-hugging-face/general.md
> +## Import the necessary libaries
```suggestion
## Import the necessary libraries
```

2022-12-20 21:14 UTC, avb-is-me commented
@Bobliuuu @sonnynomnom Is this draft fine, I checked grammar and context.  Let me know

2023-01-03 22:43 UTC, merged