ThousandthStar: make-a-pong-clone-with-pygame
codedex-io/projects pull request #46
Opened 2022-12-08 03:27 UTC by ThousandthStar

Closes issue #11 

- [x] My project tutorial topic has already been aproved by the Codédex team
- [x] My project tutorial file renders properly in `mdx`
- [x] The content written is my own, and not plagiarized from other sources
- [x] All code written is commented or documented thoroughly
- [x] I have already completed a self-review of the project tutorial 
- [x] I will comply with changes from the Codédex team about my project tutorial

**NOTE**: Missing header file. I'm assuming this will be created by the Codédex team.

2022-12-13 19:31 UTC, Bobliuuu requested changes
Hey @ThousandthStar, made some initial changes, take a look! Once you finish these, I'll do another round of review.

2022-12-13 19:31 UTC, Bobliuuu commented on projects/make-a-pong-clone-with-pygame/make-a-pong-clone-with-pygame.mdx
> +For the ball, we have a `Rect` as well, and two "acceleration" variables (similar to the players' "move" variables). We se those to
```suggestion
For the ball, we have a `Rect` as well, and two "acceleration" variables (similar to the players' "move" variables). We set those to
```

2022-12-13 19:31 UTC, Bobliuuu commented on projects/make-a-pong-clone-with-pygame/make-a-pong-clone-with-pygame.mdx
> +a random number between 2 and for to give some speed variety. We also randomize the direction of the ball by multiplying the acceleration
Between 2 and which number?

2022-12-13 19:31 UTC, Bobliuuu commented on projects/make-a-pong-clone-with-pygame/make-a-pong-clone-with-pygame.mdx
> +variables by -1, one times out of two. Here is the code for this part (it goes in the **setup** section):
Why do we need to do this? (multiply by -1)

2022-12-14 23:53 UTC, ThousandthStar commented on projects/make-a-pong-clone-with-pygame/make-a-pong-clone-with-pygame.mdx
> +variables by -1, one times out of two. Here is the code for this part (it goes in the **setup** section):
We need to do this in order to randomize the direction of the ball. If we had 0.4 as the acceleration, we'd make it always go to the right side of the screen first, since increasing `x` means going right in PyGame. This way, we randomize the direction while keeping the code cleaner imho.

2022-12-15 00:02 UTC, Bobliuuu commented on projects/make-a-pong-clone-with-pygame/make-a-pong-clone-with-pygame.mdx
> +variables by -1, one times out of two. Here is the code for this part (it goes in the **setup** section):
Can you add a bit of that explanation onto your tutorial? It makes a lot more sense once you elaborate.

2022-12-15 00:12 UTC, ThousandthStar commented
Finished resolving all of the initial changes @Bobliuuu .

2022-12-16 07:08 UTC, Goku-kun requested changes
Hi, @ThousandthStar @Bobliuuu .

I'm done with my review. I've some specific and generalized changes that I'm requesting throughout the article. Could you please review those and make changes?

Further, the GIF is asymmetrical. The paddle on the left has no margin and the paddle on the right does. So, can we update the GIF as well?

Thank you.

2022-12-16 07:08 UTC, Goku-kun commented on projects/make-a-pong-clone-with-pygame/make-a-pong-clone-with-pygame.mdx
> +`main()` function, which ends the `while` loop and closes the window.
This set of lines can be merged into a single line.

2022-12-16 07:08 UTC, Goku-kun commented on projects/make-a-pong-clone-with-pygame/make-a-pong-clone-with-pygame.mdx
> +we randomize the vertical and horizontal direction of the ball. Here is the code for this part (it goes in the **setup** section):
These lines can be merged into a single one.

2022-12-27 23:52 UTC, merged