Add Vercel Deployment Project Tutorial
codedex-io/projects pull request #91
Opened 2023-08-22 12:23 UTC by exrlla

2023-08-22 16:40 UTC, Dusch4593 requested changes
@exrlla Just left some comments/suggestions for you!

Thank you for sharing this PR with us! Super excited for this one. 🚀

2023-08-22 16:40 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +Congratulations! 🎆
```suggestion
Congratulations! 🎊 
```

2023-08-22 16:40 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +You have successfully deployed your static website using Vercel and GitHub! Now, you’re able to expand to using your own domain if you choose, or creating more websites to share with friends! 👯
```suggestion
You have successfully deployed your static website using Vercel and GitHub! Now, you can use your own domain if or create more websites to share with friends! 👯
```

2023-08-22 16:40 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +    - intermediate
```suggestion
  - javascript
  - html
  - css
  - intermediate
```

2023-08-22 16:40 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +tags:
```suggestion
bannerImage:
published: false
tags:
```

The `published` property will need to be here (and ultimately changed to `true` by @Goku-kun once it's ready to go live)

2023-08-22 16:40 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +    - intermediate
Just 2 spaces

2023-08-23 14:18 UTC, Dusch4593 requested changes
@exrlla Thanks for making those changes! We are super close to getting this published. I went through once more and have some more points of feedback. Could we take a look at these comments/suggestions?

2023-08-23 14:18 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +1. Create and/or log on to your GItHub account.
```suggestion
1. Create and/or log on to your GitHub account.
```

2023-08-23 14:18 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +1. Create and/or log on to your GItHub account.
This was probably of my doing 😂

2023-08-23 14:18 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +**Note:** If at this point you don’t have your project on a GitHub repository, [follow these instructions](https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import
```suggestion
**Note:** If you aren't sure of how to add your project to a GitHub repository, [follow these instructions](https://docs.github.com/en/migrations/importing-source-code/using-the-command-line-to-import-source-code/adding-locally-hosted-code-to-github) on adding locally hosted code to GitHub.
```

2023-08-23 14:18 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +At this point, depending on your project, it should be able to display and work locally on your computer Below is a linktr.ee clone that I created!
```suggestion
At this point, depending on your project, it should be able to display and work locally on your computer. Below is a linktr.ee clone that I created!
```

2023-08-23 14:18 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +<img src="https://raw.githubusercontent.com/codedex-io/projects/main/projects/deploy-a-website-with-vercel/images/vercel-fw-demo.gif" alt="GIF with the vercel dashboard showing a list of popular fram
```suggestion
<img src="https://raw.githubusercontent.com/codedex-io/projects/main/projects/deploy-a-website-with-vercel/images/vercel-fw-demo.gif" alt="GIF with the Vercel dashboard showing a list of popular frameworks" />
```

2023-08-23 14:18 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +<img src="https://raw.githubusercontent.com/codedex-io/projects/main/projects/deploy-a-website-with-vercel/images/vercel-loading.png" alt="the vercel dashboard with an yellow arrow and a box around t
```suggestion
<img src="https://raw.githubusercontent.com/codedex-io/projects/main/projects/deploy-a-website-with-vercel/images/vercel-loading.png" alt="The Vercel dashboard with a yellow arrow and a box around the text that shows the loading screen for deployment" />
```

2023-08-23 14:18 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +<img src="https://raw.githubusercontent.com/codedex-io/projects/main/projects/deploy-a-website-with-vercel/images/vercel-congrats.png" alt="the vercel dashboard with confetti and a congratulations sc
```suggestion
<img src="https://raw.githubusercontent.com/codedex-io/projects/main/projects/deploy-a-website-with-vercel/images/vercel-congrats.png" alt="The Vercel dashboard with confetti and a congratulations screen" />
```

2023-08-23 14:18 UTC, Dusch4593 commented on projects/deploy-a-website-with-vercel/deploy-a-website-with-vercel.mdx
> +You'll notice your GitHub repository now looks a bit different! Vercel interacted with your GitHub repository to automate the deployment process and ensure that your website stays up to date with the
Wasn't an image of the green check on GitHub somewhere around here in the draft? This image, right?

projects/deploy-a-website-with-vercel/images/Screenshot 2023-08-01 at 8.16.00 AM.png

2023-08-29 20:02 UTC, merged

2023-10-31 01:09 UTC, sonnynomnom commented
Late the to game but let's freaking goooooo! 🚀